export { FiActivity } from '@react-icons/all-files/fi/FiActivity';
export { FiAirplay } from '@react-icons/all-files/fi/FiAirplay';
export { FiGithub } from '@react-icons/all-files/fi/FiGithub';
export { FiAnchor } from '@react-icons/all-files/fi/FiAnchor';
export { FiPenTool } from '@react-icons/all-files/fi/FiPenTool';
export { FiPercent } from '@react-icons/all-files/fi/FiPercent';
export { FiPhoneCall } from '@react-icons/all-files/fi/FiPhoneCall';
export { FiMonitor } from '@react-icons/all-files/fi/FiMonitor';
export { FiLogOut } from '@react-icons/all-files/fi/FiLogOut';